- hosts: localhost
  become: true

  vars:
    username: "jroy"
    userhome: "/home/{{ username }}"

  tasks:

  - include: arch/install.yaml
    when: ansible_facts["os_family"] == "Archlinux"
  - include: ubuntu/install.yaml
    when: ansible_facts["os_family"] == "Debian"
  - include: fedora/install.yaml
    when: ansible_facts["os_family"] == "RedHat"
  # - include: tasks/configure-user.yaml
  # - include: tasks/configure-i3.yaml